export const CONTENT_SECTIONS = [
  {
    key: 'restaurant',
    label: 'Restaurant Info',
    icon: 'Dining',
    editor: 'fields',
    description: 'Core business details used across the public site, footer, contact blocks, and structured data.',
    fields: [
      { key: 'name', label: 'Restaurant name' },
      { key: 'tagline', label: 'Tagline' },
      { key: 'description', label: 'Short description', multiline: true },
      { key: 'address', label: 'Street address' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'zip', label: 'ZIP code' },
      { key: 'phone', label: 'Phone number' },
      { key: 'email', label: 'Email address' },
      { key: 'hours', label: 'Primary hours string' },
      { key: 'hours_note', label: 'Hours note', multiline: true },
      { key: 'map_embed_url', label: 'Maps URL' },
      { key: 'social_instagram', label: 'Instagram URL' },
      { key: 'social_facebook', label: 'Facebook URL' },
      { key: 'social_tripadvisor', label: 'Tripadvisor URL' },
      { key: 'social_yelp', label: 'Yelp URL' },
    ],
  },
  {
    key: 'links',
    label: 'External Links',
    icon: 'Links',
    editor: 'fields',
    description: 'Reservation, menu, pickup, delivery, and gift card destinations used by CTAs throughout the site.',
    fields: [
      { key: 'reserve', label: 'Reserve link' },
      { key: 'menu_pdf', label: 'Menu link' },
      { key: 'order_delivery', label: 'Delivery link' },
      { key: 'order_pickup', label: 'Pickup link' },
      { key: 'gift_cards', label: 'Gift card link' },
    ],
  },
  {
    key: 'hero',
    label: 'Homepage Hero',
    icon: 'Hero',
    editor: 'fields',
    description: 'Primary first impression for the homepage. Keep the copy concise, elevated, and conversion-oriented.',
    fields: [
      { key: 'eyebrow', label: 'Eyebrow' },
      { key: 'headline1', label: 'Headline line 1' },
      { key: 'headline2', label: 'Headline line 2' },
      { key: 'subheadline', label: 'Subheadline', multiline: true },
      { key: 'image_url', label: 'Hero image URL' },
      { key: 'image_alt', label: 'Hero image alt text' },
    ],
  },
  {
    key: 'story',
    label: 'Story Section',
    icon: 'Story',
    editor: 'fields',
    description: 'Brand story and trust-building proof points.',
    fields: [
      { key: 'label', label: 'Section label' },
      { key: 'quote', label: 'Quote', multiline: true },
      { key: 'body1', label: 'Body paragraph 1', multiline: true },
      { key: 'body2', label: 'Body paragraph 2', multiline: true },
      { key: 'stat1_value', label: 'Stat 1 value' },
      { key: 'stat1_label', label: 'Stat 1 label' },
      { key: 'stat2_value', label: 'Stat 2 value' },
      { key: 'stat2_label', label: 'Stat 2 label' },
      { key: 'stat3_value', label: 'Stat 3 value' },
      { key: 'stat3_label', label: 'Stat 3 label' },
      { key: 'image_url', label: 'Story image URL' },
      { key: 'image_alt', label: 'Story image alt text' },
    ],
  },
  {
    key: 'specialties',
    label: 'Specialties',
    icon: 'Menu',
    editor: 'json',
    description: 'Featured dishes on the homepage. Edit the full array in JSON format.',
    hint: 'Object with { "items": [{ "id", "tag", "name", "description", "price", "imageUrl", "imageAlt", "featured", "badge?" }] }',
  },
  {
    key: 'experiences',
    label: 'Experiences',
    icon: 'Events',
    editor: 'json',
    description: 'Homepage links into tastings, classes, music, and private dining.',
    hint: 'Object with { "items": [{ "id", "icon", "label", "title", "description", "cta", "ctaHref" }] }',
  },
  {
    key: 'menu',
    label: 'Menu Highlights',
    icon: 'Courses',
    editor: 'json',
    description: 'Homepage menu categories and highlighted dishes.',
    hint: 'Object with { "label", "headline", "note", "categories": [{ "name", "items": [{ "name", "desc", "price" }] }] }',
  },
  {
    key: 'testimonials',
    label: 'Testimonials',
    icon: 'Reviews',
    editor: 'json',
    description: 'Guest proof and review quotes used on the homepage.',
    hint: 'Object with { "label", "headline", "items": [{ "id", "text|quote", "author", "location", "source", "rating" }] }',
  },
  {
    key: 'reservation_banner',
    label: 'Reservation Banner',
    icon: 'Reserve',
    editor: 'fields',
    description: 'Conversion-focused reservation prompt used on the homepage.',
    fields: [
      { key: 'headline', label: 'Headline' },
      { key: 'sub', label: 'Supporting copy', multiline: true },
      { key: 'cta_text', label: 'CTA label' },
      { key: 'note', label: 'Small print', multiline: true },
    ],
  },
  {
    key: 'order_online',
    label: 'Order Online',
    icon: 'Takeout',
    editor: 'fields',
    description: 'Delivery and pickup support copy.',
    fields: [
      { key: 'eyebrow', label: 'Eyebrow' },
      { key: 'headline', label: 'Headline' },
      { key: 'sub', label: 'Supporting copy', multiline: true },
    ],
  },
  {
    key: 'catering',
    label: 'Catering Page',
    icon: 'Catering',
    editor: 'json',
    description: 'Full content for the /catering page — hero, intro, gallery, CTA, contact block, and SEO.',
    hint: 'Object with hero_title, hero_subtitle, hero_image_url, intro_p1, intro_p2, perfect_for: [{icon, label}], style_includes: [string], gallery: [{url, alt}], cta_heading, cta_text, cta_button_label, contact_phone, contact_email, contact_website, seo_title, seo_description, seo_og_image_url',
  },
  {
    key: 'footer',
    label: 'Footer',
    icon: 'Footer',
    editor: 'json',
    description: 'Footer navigation and supporting tagline.',
    hint: 'Object with { "tagline", "nav_items": [{ "label", "href" }] }',
  },
];

export const CONTENT_SECTION_MAP = Object.fromEntries(
  CONTENT_SECTIONS.map((section) => [section.key, section]),
);

export const CONTENT_SECTION_KEYS = CONTENT_SECTIONS.map((section) => section.key);
